<?php
return array(
    'title_company'           => array(
        'control_type' => waHtmlControl::HELP,
        'description'  => /*_wp*/'Your company info',
    ),
    'logo'           => array(
        'value'        => '',
        'title'        => /*_wp*/'Logo',
        'description'  => '',
        'control_type' => waHtmlControl::FILE,
        'subject'      => 'printform',
        'img_path'     => 'plugins/invoice/',
    ),
    'name'           => array(
        'value'        => 'Company name',
        'title'        => /*_wp*/'Company name',
        'description'  => '',
        'placeholder'  => /*_wp*/'Company name',
        'control_type' => waHtmlControl::INPUT,
        'subject'      => 'printform',
    ),
    'tagline'        => array(
        'value'        => '',
        'title'        => /*_wp*/'Tagline',
        'description'  => '',
        'control_type' => waHtmlControl::INPUT,
        'subject'      => 'printform',
    ),
    'address_street' => array(
        'value'        => '',
        'placeholder'  => /*_wp*/'Street address',
        'title'        => /*_wp*/'Street address',
        'description'  => '',
        'control_type' => waHtmlControl::INPUT,
        'subject'      => 'printform',
    ),
    'address_city'   => array(
        'value'        => '',
        'placeholder'  => /*_wp*/'City, St, ZIP',
        'title'        => /*_wp*/'City, state',
        'description'  => '',
        'control_type' => waHtmlControl::INPUT,
        'subject'      => 'printform',
    ),
    'phone'          => array(
        'value'        => '',
        'title'        => /*_wp*/'Phone No.',
        'description'  => '',
        'control_type' => waHtmlControl::INPUT,
        'subject'      => 'printform',
    ),
    'fax'            => array(
        'value'        => '',
        'title'        => /*_wp*/'Fax No.',
        'description'  => '',
        'control_type' => waHtmlControl::INPUT,
        'subject'      => 'printform',
    ),
    'title_client'           => array(
        'control_type' => waHtmlControl::HELP,
        'description'  => /*_wp*/'Client info',
    ),
    'contact_company'   => array(
        'value'        => 'company',
        'title'        => /*_wp*/'Company name',
        'description'  => '',
        'control_type' => waHtmlControl::CONTACTFIELD,
        'subject'      => 'printform',
    ),
    'contact_phone'          => array(
        'value'        => 'phone',
        'title'        => /*_wp*/'Phone No.',
        'description'  => '',
        'control_type' => waHtmlControl::CONTACTFIELD,
        'subject'      => 'printform',
    ),
    'title_common'           => array(
        'control_type' => waHtmlControl::HELP,
        'description'  => /*_wp*/'Common settings',
    ),
    'comments'       => array(
        'value'        =>'',
        'title'        => /*_wp*/'Comments',
        'description'  => /*_wp*/'HTML code allowed',
        'wisywig'      => true,
        'control_type' => waHtmlControl::TEXTAREA,
        'subject'      => 'printform',
    ),
);
