<?php

class shopMigratePlugin extends shopPlugin
{
    private static $developer = false;

    public static function getTransports()
    {
        $transports = array(
            ''               => array(
                'value'       => '',
                'title'       => _wp('Select platform'),
                'description' => '',
            ),
            'ozon'           => array(
                'value'       => 'ozon',
                'title'       => 'Ozon',
                'description' => _wp('Import products via Ozon seller API'),
                'group'       => _wp('Marketplaces'),
                'locale'      => array(
                    'ru_RU',
                )
            ),
            'tilda'    => array(
                'value'       => 'tilda',
                'title'       => 'Tilda',
                'description' => _wp('Import data from Tilda using the generated YML feed provided by the source store.'),
                'group'       => 'CMS',
                'locale'      => array(
                    'ru_RU',
                )
            ),
            'insales'        => array(
                'value'       => 'insales',
                'title'       => 'InSales',
                'description' => _wp('Import via the official InSales API using your store credentials.'),
                'group'       => 'CMS',
                'locale'      => array(
                    'ru_RU',
                )
            ),
            'woocommerce'    => array(
                'value'       => 'woocommerce',
                'title'       => 'Wordpress WooCommerce',
                'description' => _wp('Migrate data from <a href="http://www.woothemes.com/woocommerce/" target="_blank">WooCommerce</a>-powered online store (a plugin that enables ecommerce functionality for WordPress).'),
                'group'       => 'CMS',
            ),
            'opencart'       => array(
                'value'       => 'opencart',
                'title'       => _wp('OpenCart 1.5.x with Web API 1.0 plugin'),
                'description' => _wp('Migrate data from <a href="http://www.opencart.com" target="_blank">OpenCart</a>-powered online store via Web API 1.0 OpenCart plugin.<br><br><strong>IMPORTANT:</strong> <a href="http://www.opencart.com/index.php?route=extension/extension/info&extension_id=14754" target="_blank">Opencart API plugin</a> must be installed to export your data from OpenCart.'),
                'group'       => 'CMS',
            ),
            'magento'        => array(
                'value'       => 'magento',
                'title'       => 'Magento',
                'description' => _wp('Import data from an online store powered by <a href="http://magento.com" target="_blank">Magento</a> CE 1.7 and later or Magento EE 1.12 and later.'),
                'group'       => 'CMS',
            ),
            'simpla'         => array(
                'value'       => 'simpla',
                'title'       => 'Simpla',
                'description' => _wp('Import products and customers from Simpla CMS using the REST API.'),
                'group'       => 'CMS',
                'locale'      => array(
                    'ru_RU',
                )
            ),
            'phpshop'        => array(
                'value'       => 'phpshop',
                'title'       => 'PHPShop',
                'description' => _wp('Import data from PHPShop using a YML export generated by the source store.'),
                'group'       => 'CMS',
                'locale'      => array(
                    'ru_RU',
                )
            ),
            'storelandru'    => array(
                'value'       => 'storelandru',
                'title'       => 'StoreLand',
                'description' => _wp('Import data from StoreLand using the generated YML feed provided by the source store.'),
                'group'       => 'CMS',
                'locale'      => array(
                    'ru_RU',
                )

            ),
            'yml'            => array(
                'value'       => 'yml',
                'title'       => _wp('YML feed file'),
                'description' => '',
                'group'       => _wp('YML'),
                'locale'      => array(
                    'ru_RU',
                )
            ),
            'webasystsame'   => array(
                'value'       => 'webasystsame',
                'title'       => _wp('WebAsyst Shop-Script (old version) on the same server'),
                'description' => _wp(
                    'Migrate aux pages, categories, products with params, features, images and eproduct files'
                ),
                'group'       => 'Webasyst',
            ),
            'webasystremote' => array(
                'value'       => 'webasystremote',
                'title'       => _wp('WebAsyst Shop-Script (old version) on a remote server'),
                'description' => '',
                'group'       => 'Webasyst',
            ),
        );


        return self::$developer ? array(
                '' => array(
                    'value'       => '',
                    'title'       => _wp('Select platform'),
                    'description' => '',
                )
            ) + shopMigrateTransport::enumerate() : $transports;
    }

    public function getWelcomeUrl($data = array())
    {
        $platform = ifset($data['platform']);
        return $platform ? sprintf('?action=importexport#/migrate/%s/', $platform) : null;
    }

    public function backendWelcomeHandler()
    {
        return [
            'form_bottom' => (new shopMigratePluginWelcomeAction())->display(),
        ];
    }
}
