<?php
return array(
    'name'        => /*_w*/('Shop'),
    'description' => /*_w*/('Shop-Script is a robust shopping cart software that allows you to quickly establish your own online store and sell online.'),
    'icon'        => array(
        16 => 'img/shop16.png',
        24 => 'img/shop24.png',
        48 => 'img/shop.png',
        96 => 'img/shop96.png',
    ),
    'sash_color' => '#a5cb19',
    'rights'      => true,
    'frontend'    => true,
    'auth'        => true,
    'themes'      => true,
    'plugins'     => true,
    'pages'       => true,
    'mobile'      => true,
    'my_account'  => true,
    'version'     => '6.3.0',
    'critical'    => '6.3.0',
    'vendor'      => 'webasyst',
    'csrf'        => true,
    'payment_plugins' => true,
    'shipping_plugins' => true,
    'sms_plugins' => true,
    'license'     => 'commercial',
);
