<?php

$api_rules = [
    'api/v1/shop/?' => 'frontend/apiShop',
    'api/v1/promos/?' => 'frontend/apiPromos',
    'api/v1/shipping/list/?' => 'frontend/apiShippingList',
    'api/v1/shipping/costs/?' => 'frontend/apiShippingCosts',
    'api/v1/customer_token/?' => 'frontend/apiCustomerToken',
    'api/v1/order/calculate/?' => 'frontend/apiOrderCalculate',
    'api/v1/order/create/?' => 'frontend/apiOrderCreate',
    'api/v1/cart/?' => 'frontend/apiCart',
    'api/v1/category/<category_id:\d+>/products/?'                          => 'frontend/apiProductsSearch',
    'api/v1/set/<set_id:[^/]+>/products/?'                                  => 'frontend/apiProductsSearch',
    'api/v1/tag/<tag_id:[^/]+>/products/?'                                  => 'frontend/apiProductsSearch',
    'api/v1/products/<product_ids:[\d,]+>/?'                                => 'frontend/apiProductsSearch',
    'api/v1/products/search/?'                                              => 'frontend/apiProductsSearch',
    'api/v1/product/<product_id_cross_selling:\d+>/related/cross_selling/?' => 'frontend/apiProductsSearch',
    'api/v1/product/<product_id_upselling:\d+>/related/upselling/?'         => 'frontend/apiProductsSearch',
    'api/v1/product/<id>/reviews/add/?' => 'frontend/apiProductReviewAdd',
    'api/v1/product/<id>/reviews/?' => 'frontend/apiProductReviews',
    'api/v1/product/<id>/?' => 'frontend/apiProduct',
    'api/v1/categories/?' => 'frontend/apiCategories',
    'api/swagger/v<api_version_number:[\d]+>.yaml' => 'frontend/apiYaml',
    'api/v1/*' => 'frontend/apiErr404',
];

return array(
    // default
    // url to category: /category/categoryurl/
    // url to product: /producturl/
    0 => $api_rules + array(
        '' => 'frontend/',
        'login/' => 'login/',
        'forgotpassword/' => 'forgotpassword/',
        'signup/' => 'signup/',
        'search/' => 'frontend/search',
        'paymentlink/<hash>/?' => 'frontend/paymentLink',
        'data/regions/' => 'frontend/regions',
        'data/shipping/<plugin_id:\d+>/<action_id>/' => 'frontend/shippingPlugin',
        'data/shipping/' => 'frontend/shipping',
        'cart/' => 'frontend/cart',
        'checkout/' => 'frontend/checkout',
        'checkout/<step:[^/]+>/?' => 'frontend/checkout',
        'cart/<action:add|save|delete>/' => 'frontendCart',
        'order/cart/<action:get|add|save|render|productdialog|customertoken>/?' => 'frontendOrderCart',
        'order/confirmation/<action:>/' => 'frontendOrderConfirmation',
        'order/<action:>/' => 'frontendOrder',
        'order/' => 'frontend/order',
        'compare/' => 'frontend/compare',
        'compare/<id:[\d,]+>/' => 'frontend/compare',
        'tag/<tag>/' => 'frontend/tag',
        'category/<category_url>/' => 'frontend/category',
        'buybuttons/' => 'frontend/buybuttons',
        'my/order/<id>/<code>/print/<form_type:(payment|shipping|form)>/<form_id>/?' => 'frontend/myOrderPrintform',
        'my/order/<id>/print/<form_type:(payment|shipping|form)>/<form_id>/?' => 'frontend/myOrderPrintform',
        'my/order/<id>/download/<code>/<item>/?' => 'frontend/myOrderDownload',
        'my/order/<id>/<code:[^/]+>/?' => 'frontend/myOrderByCode',
        'my/order/<id>/?' => array(
            'module' => 'frontend',
            'action' => 'myOrder',
            'secure' => true,
        ),
        'my/profile/?' => array(
            'module' => 'frontend',
            'action' => 'myProfile',
            'secure' => true,
        ),
        'my/orders/?' => array(
            'module' => 'frontend',
            'action' => 'myOrders',
            'secure' => true,
        ),
        'my/affiliate/?' => array(
            'module' => 'frontend',
            'action' => 'myAffiliate',
            'secure' => true,
        ),
        'my/?' => array(
            'module' => 'frontend',
            'action' => 'my',
            'secure' => true,
        ),
        '<product_url:[^/]+>/reviews/' => 'frontend/productReviews',
        '<product_url:[^/]+>/reviews/add/' => 'frontend/productReviewsAdd',
        '<product_url:[^/]+>/<page_url>/' => 'frontend/productPage',
        '<product_url:[^/]+>/' => 'frontend/product',
    ),

    1 => $api_rules + array(
        '' => 'frontend/',
        'login/' => 'login/',
        'forgotpassword/' => 'forgotpassword/',
        'signup/' => 'signup/',
        'search/' => 'frontend/search',
        'paymentlink/<hash>/?' => 'frontend/paymentLink',
        'data/regions/' => 'frontend/regions',
        'data/shipping/<plugin_id:\d+>/<action_id>/' => 'frontend/shippingPlugin',
        'data/shipping/' => 'frontend/shipping',
        'cart/' => 'frontend/cart',
        'checkout/' => 'frontend/checkout',
        'checkout/<step:[^/]+>/?' => 'frontend/checkout',
        'cart/<action:add|save|delete>/' => 'frontendCart',
        'order/cart/<action:get|add|save|render|productdialog|customertoken>/?' => 'frontendOrderCart',
        'order/confirmation/<action:>/' => 'frontendOrderConfirmation',
        'order/<action:>/' => 'frontendOrder',
        'order/' => 'frontend/order',
        'compare/' => 'frontend/compare',
        'compare/<id:[\d,]+>/' => 'frontend/compare',
        'tag/<tag>/' => 'frontend/tag',
        'category/<category_url>/' => 'frontend/category',
        'buybuttons/' => 'frontend/buybuttons',
        'my/order/<id>/<code>/print/<form_type:(payment|shipping|form)>/<form_id>/?' => 'frontend/myOrderPrintform',
        'my/order/<id>/print/<form_type:(payment|shipping|form)>/<form_id>/?' => 'frontend/myOrderPrintform',
        'my/order/<id>/download/<code>/<item>/?' => 'frontend/myOrderDownload',
        'my/order/<id>/<code:[^/]+>/?' => 'frontend/myOrderByCode',
        'my/order/<id>/?' => array(
            'url' => 'my/order/<id>/?',
            'module' => 'frontend',
            'action' => 'myOrder',
            'secure' => true,
        ),
        'my/profile/?' => array(
            'url' => 'my/profile/?',
            'module' => 'frontend',
            'action' => 'myProfile',
            'secure' => true,
        ),
        'my/orders/?' => array(
            'url' => 'my/orders/?',
            'module' => 'frontend',
            'action' => 'myOrders',
            'secure' => true,
        ),
        'my/affiliate/?' => array(
            'module' => 'frontend',
            'action' => 'myAffiliate',
            'secure' => true,
        ),
        'my/?' => array(
            'url' => 'my/?',
            'module' => 'frontend',
            'action' => 'my',
            'secure' => true,
        ),
        'product/<product_url:[^/]+>/reviews/' => 'frontend/productReviews',
        'product/<product_url:[^/]+>/reviews/add/' => 'frontend/productReviewsAdd',
        'product/<product_url:[^/]+>/<page_url>/' => 'frontend/productPage',
        'product/<product_url:[^/]+>/' => 'frontend/product',
    ),

    2 => $api_rules + array(
        '' => 'frontend/',
        'login/' => 'login/',
        'forgotpassword/' => 'forgotpassword/',
        'signup/' => 'signup/',
        'search/' => 'frontend/search',
        'paymentlink/<hash>/?' => 'frontend/paymentLink',
        'data/regions/' => 'frontend/regions',
        'data/shipping/<plugin_id:\d+>/<action_id>/' => 'frontend/shippingPlugin',
        'data/shipping/' => 'frontend/shipping',
        'cart/' => 'frontend/cart',
        'checkout/' => 'frontend/checkout',
        'checkout/<step:[^/]+>/?' => 'frontend/checkout',
        'cart/<action:add|save|delete>/' => 'frontendCart',
        'order/cart/<action:get|add|save|render|productdialog|customertoken>/?' => 'frontendOrderCart',
        'order/confirmation/<action:>/' => 'frontendOrderConfirmation',
        'order/<action:>/' => 'frontendOrder',
        'order/' => 'frontend/order',
        'compare/' => 'frontend/compare',
        'compare/<id:[\d,]+>/' => 'frontend/compare',
        'tag/<tag>/' => 'frontend/tag',
        'buybuttons/' => 'frontend/buybuttons',
        'my/order/<id>/<code>/print/<form_type:(payment|shipping|form)>/<form_id>/?' => 'frontend/myOrderPrintform',
        'my/order/<id>/print/<form_type:(payment|shipping|form)>/<form_id>/?' => 'frontend/myOrderPrintform',
        'my/order/<id>/download/<code>/<item>/?' => 'frontend/myOrderDownload',
        'my/order/<id>/<code:[^/]+>/?' => 'frontend/myOrderByCode',
        'my/order/<id>/?' => array(
            'url' => 'my/order/<id>/?',
            'module' => 'frontend',
            'action' => 'myOrder',
            'secure' => true,
        ),
        'my/profile/?' => array(
            'url' => 'my/profile/?',
            'module' => 'frontend',
            'action' => 'myProfile',
            'secure' => true,
        ),
        'my/orders/?' => array(
            'url' => 'my/orders/?',
            'module' => 'frontend',
            'action' => 'myOrders',
            'secure' => true,
        ),
        'my/affiliate/?' => array(
            'module' => 'frontend',
            'action' => 'myAffiliate',
            'secure' => true,
        ),
        'my/?' => array(
            'url' => 'my/?',
            'module' => 'frontend',
            'action' => 'my',
            'secure' => true,
        ),
        '<product_url:[^/]+>/' => 'frontend/product',
        '<category_url>/?<product_url:[^/]+>/reviews/' => 'frontend/productReviews',
        '<category_url>/?<product_url:[^/]+>/reviews/add/' => 'frontend/productReviewsAdd',
        '<category_url>/<product_url:[^/]+>/' => 'frontend/product',
        '<category_url>/<product_url:[^/]+>/<page_url>/' => 'frontend/productPage',
        '<category_url>/' => 'frontend/category',
    ),
    3 => $api_rules + [
    ],
);