<?php

return array(
    'shop_migrate_ozon_snapshots' => array(
        'id' => array('int', 11, 'unsigned' => 1, 'autoincrement' => 1),
        'status' => array('varchar', 16, 'null' => 0, 'default' => 'draft'),
        'meta' => array('text', 'null' => 1),
        'created_at' => array('datetime', 'null' => 0),
        'updated_at' => array('datetime', 'null' => 0),
        ':keys' => array(
            'PRIMARY' => array('id'),
            'status' => array('status'),
        ),
        ':options' => array('charset' => 'utf8mb4', 'collate' => 'utf8mb4_general_ci'),
    ),
    'shop_migrate_ozon_products' => array(
        'id' => array('int', 11, 'unsigned' => 1, 'autoincrement' => 1),
        'snapshot_id' => array('int', 11, 'unsigned' => 1, 'null' => 0),
        'product_id' => array('bigint', 20, 'unsigned' => 1, 'null' => 0),
        'offer_id' => array('varchar', 128, 'null' => 0, 'default' => ''),
        'description_category_id' => array('bigint', 20, 'unsigned' => 1, 'null' => 0),
        'type_id' => array('bigint', 20, 'unsigned' => 1, 'null' => 0),
        'name' => array('varchar', 255, 'null' => 0, 'default' => ''),
        'flags' => array('text', 'null' => 1),
        'details' => array('longtext', 'null' => 1),
        'created_at' => array('datetime', 'null' => 0),
        'updated_at' => array('datetime', 'null' => 0),
        ':keys' => array(
            'PRIMARY' => array('id'),
            'snapshot_product' => array('snapshot_id', 'product_id', 'unique' => 1),
            'snapshot_offer' => array('snapshot_id', 'offer_id'),
        ),
        ':options' => array('charset' => 'utf8mb4', 'collate' => 'utf8mb4_general_ci'),
    ),
    'shop_migrate_ozon_categories' => array(
        'id' => array('int', 11, 'unsigned' => 1, 'autoincrement' => 1),
        'snapshot_id' => array('int', 11, 'unsigned' => 1, 'null' => 0),
        'description_category_id' => array('bigint', 20, 'unsigned' => 1, 'null' => 0),
        'parent_id' => array('bigint', 20, 'unsigned' => 1, 'null' => 1),
        'name' => array('varchar', 255, 'null' => 0, 'default' => ''),
        'path' => array('varchar', 1024, 'null' => 0, 'default' => ''),
        'level' => array('smallint', 3, 'unsigned' => 1, 'null' => 0, 'default' => 0),
        ':keys' => array(
            'PRIMARY' => array('id'),
            'snapshot_category' => array('snapshot_id', 'description_category_id', 'unique' => 1),
        ),
        ':options' => array('charset' => 'utf8mb4', 'collate' => 'utf8mb4_general_ci'),
    ),
    'shop_migrate_ozon_attributes' => array(
        'id' => array('int', 11, 'unsigned' => 1, 'autoincrement' => 1),
        'snapshot_id' => array('int', 11, 'unsigned' => 1, 'null' => 0),
        'description_category_id' => array('bigint', 20, 'unsigned' => 1, 'null' => 0),
        'type_id' => array('bigint', 20, 'unsigned' => 1, 'null' => 0),
        'attribute_id' => array('bigint', 20, 'unsigned' => 1, 'null' => 0),
        'name' => array('varchar', 255, 'null' => 0, 'default' => ''),
        'type' => array('varchar', 32, 'null' => 0, 'default' => ''),
        'unit' => array('varchar', 64, 'null' => 1),
        'is_required' => array('tinyint', 1, 'null' => 0, 'default' => 0),
        'is_collection' => array('tinyint', 1, 'null' => 0, 'default' => 0),
        'meta' => array('text', 'null' => 1),
        ':keys' => array(
            'PRIMARY' => array('id'),
            'snapshot_attribute' => array('snapshot_id', 'attribute_id', 'unique' => 1),
        ),
        ':options' => array('charset' => 'utf8mb4', 'collate' => 'utf8mb4_general_ci'),
    ),
    'shop_migrate_ozon_attribute_values' => array(
        'id' => array('int', 11, 'unsigned' => 1, 'autoincrement' => 1),
        'snapshot_id' => array('int', 11, 'unsigned' => 1, 'null' => 0),
        'product_id' => array('bigint', 20, 'unsigned' => 1, 'null' => 0),
        'attribute_id' => array('bigint', 20, 'unsigned' => 1, 'null' => 0),
        'dictionary_value_id' => array('bigint', 20, 'unsigned' => 1, 'null' => 1),
        'value' => array('text', 'null' => 1),
        'position' => array('int', 11, 'unsigned' => 1, 'null' => 0, 'default' => 0),
        ':keys' => array(
            'PRIMARY' => array('id'),
            'snapshot_attr_product' => array('snapshot_id', 'product_id', 'attribute_id', 'position', 'unique' => 1),
        ),
        ':options' => array('charset' => 'utf8mb4', 'collate' => 'utf8mb4_general_ci'),
    ),
    'shop_migrate_ozon_warehouses' => array(
        'id' => array('int', 11, 'unsigned' => 1, 'autoincrement' => 1),
        'snapshot_id' => array('int', 11, 'unsigned' => 1, 'null' => 0),
        'warehouse_id' => array('bigint', 20, 'unsigned' => 1, 'null' => 0),
        'name' => array('varchar', 255, 'null' => 0, 'default' => ''),
        'type' => array('varchar', 32, 'null' => 0, 'default' => ''),
        'created_at' => array('datetime', 'null' => 0),
        ':keys' => array(
            'PRIMARY' => array('id'),
            'snapshot_warehouse' => array('snapshot_id', 'warehouse_id', 'unique' => 1),
        ),
        ':options' => array('charset' => 'utf8mb4', 'collate' => 'utf8mb4_general_ci'),
    ),
    'shop_migrate_ozon_stocks' => array(
        'id' => array('int', 11, 'unsigned' => 1, 'autoincrement' => 1),
        'snapshot_id' => array('int', 11, 'unsigned' => 1, 'null' => 0),
        'product_id' => array('bigint', 20, 'unsigned' => 1, 'null' => 0),
        'offer_id' => array('varchar', 128, 'null' => 0, 'default' => ''),
        'warehouse_id' => array('bigint', 20, 'unsigned' => 1, 'null' => 0),
        'quantity' => array('decimal', '15,3', 'null' => 0, 'default' => '0.000'),
        'updated_at' => array('datetime', 'null' => 0),
        ':keys' => array(
            'PRIMARY' => array('id'),
            'snapshot_stock' => array('snapshot_id', 'product_id', 'warehouse_id'),
            'snapshot_offer_stock' => array('snapshot_id', 'offer_id', 'warehouse_id'),
        ),
        ':options' => array('charset' => 'utf8mb4', 'collate' => 'utf8mb4_general_ci'),
    ),
    'shop_migrate_ozon_type_map' => array(
        'id' => array('int', 11, 'unsigned' => 1, 'autoincrement' => 1),
        'snapshot_id' => array('int', 11, 'unsigned' => 1, 'null' => 0),
        'description_category_id' => array('bigint', 20, 'unsigned' => 1, 'null' => 0),
        'type_id' => array('bigint', 20, 'unsigned' => 1, 'null' => 0),
        'mode' => array('varchar', 16, 'null' => 0, 'default' => 'auto'),
        'shop_type_id' => array('int', 11, 'unsigned' => 1, 'null' => 1),
        'shop_type_name' => array('varchar', 255, 'null' => 1),
        'created_at' => array('datetime', 'null' => 0),
        'updated_at' => array('datetime', 'null' => 0),
        ':keys' => array(
            'PRIMARY' => array('id'),
            'snapshot_type' => array('snapshot_id', 'description_category_id', 'type_id', 'unique' => 1),
        ),
        ':options' => array('charset' => 'utf8mb4', 'collate' => 'utf8mb4_general_ci'),
    ),
    'shop_migrate_ozon_category_map' => array(
        'id' => array('int', 11, 'unsigned' => 1, 'autoincrement' => 1),
        'snapshot_id' => array('int', 11, 'unsigned' => 1, 'null' => 0),
        'description_category_id' => array('bigint', 20, 'unsigned' => 1, 'null' => 0),
        'mode' => array('varchar', 16, 'null' => 0, 'default' => 'auto'),
        'shop_category_id' => array('int', 11, 'unsigned' => 1, 'null' => 1),
        'action' => array('varchar', 16, 'null' => 0, 'default' => 'auto'),
        'created_at' => array('datetime', 'null' => 0),
        'updated_at' => array('datetime', 'null' => 0),
        ':keys' => array(
            'PRIMARY' => array('id'),
            'snapshot_category' => array('snapshot_id', 'description_category_id', 'unique' => 1),
        ),
        ':options' => array('charset' => 'utf8mb4', 'collate' => 'utf8mb4_general_ci'),
    ),
    'shop_migrate_ozon_stock_map' => array(
        'id' => array('int', 11, 'unsigned' => 1, 'autoincrement' => 1),
        'snapshot_id' => array('int', 11, 'unsigned' => 1, 'null' => 0),
        'warehouse_id' => array('bigint', 20, 'unsigned' => 1, 'null' => 0),
        'mode' => array('varchar', 16, 'null' => 0, 'default' => 'auto'),
        'shop_stock_id' => array('int', 11, 'unsigned' => 1, 'null' => 1),
        'action' => array('varchar', 16, 'null' => 0, 'default' => 'auto'),
        'created_at' => array('datetime', 'null' => 0),
        'updated_at' => array('datetime', 'null' => 0),
        ':keys' => array(
            'PRIMARY' => array('id'),
            'snapshot_stock' => array('snapshot_id', 'warehouse_id', 'unique' => 1),
        ),
        ':options' => array('charset' => 'utf8mb4', 'collate' => 'utf8mb4_general_ci'),
    ),
    'shop_migrate_ozon_feature_map' => array(
        'id' => array('int', 11, 'unsigned' => 1, 'autoincrement' => 1),
        'snapshot_id' => array('int', 11, 'unsigned' => 1, 'null' => 0),
        'attribute_id' => array('bigint', 20, 'unsigned' => 1, 'null' => 0),
        'mode' => array('varchar', 16, 'null' => 0, 'default' => 'auto'),
        'shop_feature_id' => array('int', 11, 'unsigned' => 1, 'null' => 1),
        'shop_feature_code' => array('varchar', 64, 'null' => 1),
        'action' => array('varchar', 16, 'null' => 0, 'default' => 'auto'),
        'created_at' => array('datetime', 'null' => 0),
        'updated_at' => array('datetime', 'null' => 0),
        ':keys' => array(
            'PRIMARY' => array('id'),
            'snapshot_feature' => array('snapshot_id', 'attribute_id', 'unique' => 1),
        ),
        ':options' => array('charset' => 'utf8mb4', 'collate' => 'utf8mb4_general_ci'),
    ),
    'shop_migrate_ozon_product_map' => array(
        'id' => array('int', 11, 'unsigned' => 1, 'autoincrement' => 1),
        'offer_id' => array('varchar', 128, 'null' => 0, 'default' => ''),
        'shop_product_id' => array('int', 11, 'unsigned' => 1, 'null' => 0),
        'shop_sku_id' => array('int', 11, 'unsigned' => 1, 'null' => 1),
        'ozon_product_id' => array('bigint', 20, 'unsigned' => 1, 'null' => 1),
        'created_at' => array('datetime', 'null' => 0),
        'updated_at' => array('datetime', 'null' => 0),
        ':keys' => array(
            'PRIMARY' => array('id'),
            'offer_unique' => array('offer_id', 'unique' => 1),
        ),
        ':options' => array('charset' => 'utf8mb4', 'collate' => 'utf8mb4_general_ci'),
    ),
);
