<?php
return array(
    'shop_migrate_ozon_snapshots' => array(
        'id' => array('int', 11, 'unsigned' => 1, 'null' => 0, 'autoincrement' => 1),
        'status' => array('varchar', 16, 'null' => 0, 'default' => 'draft'),
        'meta' => array('longtext'),
        'created_at' => array('datetime', 'null' => 0),
        'updated_at' => array('datetime', 'null' => 0),
        ':keys' => array(
            'PRIMARY' => 'id',
            'status' => 'status',
        ),
        ':options' => array('charset' => 'utf8mb4', 'collate' => 'utf8mb4_general_ci'),
    ),
    'shop_migrate_ozon_products' => array(
        'id' => array('int', 11, 'unsigned' => 1, 'null' => 0, 'autoincrement' => 1),
        'snapshot_id' => array('int', 11, 'unsigned' => 1, 'null' => 0),
        'product_id' => array('bigint', 20, 'unsigned' => 1, 'null' => 0),
        'offer_id' => array('varchar', 128, 'null' => 0, 'default' => ''),
        'ozon_sku' => array('varchar', 64),
        'description_category_id' => array('bigint', 20, 'unsigned' => 1, 'null' => 0),
        'type_id' => array('bigint', 20, 'unsigned' => 1, 'null' => 0),
        'model_id' => array('bigint', 20, 'unsigned' => 1, 'null' => 0, 'default' => '0'),
        'model_count' => array('int', 11, 'unsigned' => 1, 'null' => 0, 'default' => '0'),
        'name' => array('varchar', 255, 'null' => 0, 'default' => ''),
        'flags' => array('text'),
        'details' => array('longtext'),
        'created_at' => array('datetime', 'null' => 0),
        'updated_at' => array('datetime', 'null' => 0),
        ':keys' => array(
            'PRIMARY' => 'id',
            'snapshot_product' => array('snapshot_id', 'product_id', 'unique' => 1),
            'snapshot_offer' => array('snapshot_id', 'offer_id'),
            'snapshot_model' => array('snapshot_id', 'model_id', 'product_id'),
        ),
        ':options' => array('charset' => 'utf8mb4', 'collate' => 'utf8mb4_general_ci'),
    ),
    'shop_migrate_ozon_categories' => array(
        'id' => array('int', 11, 'unsigned' => 1, 'null' => 0, 'autoincrement' => 1),
        'snapshot_id' => array('int', 11, 'unsigned' => 1, 'null' => 0),
        'description_category_id' => array('bigint', 20, 'unsigned' => 1, 'null' => 0),
        'parent_id' => array('bigint', 20, 'unsigned' => 1),
        'name' => array('varchar', 255, 'null' => 0, 'default' => ''),
        'path' => array('varchar', 1024, 'null' => 0, 'default' => ''),
        'level' => array('smallint', 3, 'unsigned' => 1, 'null' => 0, 'default' => '0'),
        ':keys' => array(
            'PRIMARY' => 'id',
            'snapshot_category' => array('snapshot_id', 'description_category_id', 'unique' => 1),
        ),
        ':options' => array('charset' => 'utf8mb4', 'collate' => 'utf8mb4_general_ci'),
    ),
    'shop_migrate_ozon_attributes' => array(
        'id' => array('int', 11, 'unsigned' => 1, 'null' => 0, 'autoincrement' => 1),
        'snapshot_id' => array('int', 11, 'unsigned' => 1, 'null' => 0),
        'description_category_id' => array('bigint', 20, 'unsigned' => 1, 'null' => 0),
        'type_id' => array('bigint', 20, 'unsigned' => 1, 'null' => 0),
        'attribute_id' => array('bigint', 20, 'unsigned' => 1, 'null' => 0),
        'name' => array('varchar', 255, 'null' => 0, 'default' => ''),
        'type' => array('varchar', 32, 'null' => 0, 'default' => ''),
        'unit' => array('varchar', 64),
        'is_required' => array('tinyint', 1, 'null' => 0, 'default' => '0'),
        'is_collection' => array('tinyint', 1, 'null' => 0, 'default' => '0'),
        'meta' => array('text'),
        ':keys' => array(
            'PRIMARY' => 'id',
            'snapshot_attribute' => array('snapshot_id', 'attribute_id', 'unique' => 1),
        ),
        ':options' => array('charset' => 'utf8mb4', 'collate' => 'utf8mb4_general_ci'),
    ),
    'shop_migrate_ozon_attribute_values' => array(
        'id' => array('int', 11, 'unsigned' => 1, 'null' => 0, 'autoincrement' => 1),
        'snapshot_id' => array('int', 11, 'unsigned' => 1, 'null' => 0),
        'product_id' => array('bigint', 20, 'unsigned' => 1, 'null' => 0),
        'attribute_id' => array('bigint', 20, 'unsigned' => 1, 'null' => 0),
        'dictionary_value_id' => array('bigint', 20, 'unsigned' => 1),
        'value' => array('text'),
        'position' => array('int', 11, 'unsigned' => 1, 'null' => 0, 'default' => '0'),
        ':keys' => array(
            'PRIMARY' => 'id',
            'snapshot_attr_product' => array('snapshot_id', 'product_id', 'attribute_id', 'position', 'unique' => 1),
        ),
        ':options' => array('charset' => 'utf8mb4', 'collate' => 'utf8mb4_general_ci'),
    ),
    'shop_migrate_ozon_warehouses' => array(
        'id' => array('int', 11, 'unsigned' => 1, 'null' => 0, 'autoincrement' => 1),
        'snapshot_id' => array('int', 11, 'unsigned' => 1, 'null' => 0),
        'warehouse_id' => array('bigint', 20, 'unsigned' => 1, 'null' => 0),
        'name' => array('varchar', 255, 'null' => 0, 'default' => ''),
        'type' => array('varchar', 32, 'null' => 0, 'default' => ''),
        'created_at' => array('datetime', 'null' => 0),
        ':keys' => array(
            'PRIMARY' => 'id',
            'snapshot_warehouse' => array('snapshot_id', 'warehouse_id', 'unique' => 1),
        ),
        ':options' => array('charset' => 'utf8mb4', 'collate' => 'utf8mb4_general_ci'),
    ),
    'shop_migrate_ozon_stocks' => array(
        'id' => array('int', 11, 'unsigned' => 1, 'null' => 0, 'autoincrement' => 1),
        'snapshot_id' => array('int', 11, 'unsigned' => 1, 'null' => 0),
        'product_id' => array('bigint', 20, 'unsigned' => 1, 'null' => 0),
        'offer_id' => array('varchar', 128, 'null' => 0, 'default' => ''),
        'warehouse_id' => array('bigint', 20, 'unsigned' => 1, 'null' => 0),
        'quantity' => array('decimal', "15,3", 'null' => 0, 'default' => '0.000'),
        'updated_at' => array('datetime', 'null' => 0),
        ':keys' => array(
            'PRIMARY' => 'id',
            'snapshot_stock' => array('snapshot_id', 'product_id', 'warehouse_id', 'unique' => 1),
            'snapshot_offer_stock' => array('snapshot_id', 'offer_id', 'warehouse_id'),
        ),
        ':options' => array('charset' => 'utf8mb4', 'collate' => 'utf8mb4_general_ci'),
    ),
    'shop_migrate_ozon_type_map' => array(
        'id' => array('int', 11, 'unsigned' => 1, 'null' => 0, 'autoincrement' => 1),
        'snapshot_id' => array('int', 11, 'unsigned' => 1, 'null' => 0),
        'description_category_id' => array('bigint', 20, 'unsigned' => 1, 'null' => 0),
        'type_id' => array('bigint', 20, 'unsigned' => 1, 'null' => 0),
        'mode' => array('varchar', 16, 'null' => 0, 'default' => 'auto'),
        'shop_type_id' => array('int', 11, 'unsigned' => 1),
        'shop_type_name' => array('varchar', 255),
        'created_at' => array('datetime', 'null' => 0),
        'updated_at' => array('datetime', 'null' => 0),
        ':keys' => array(
            'PRIMARY' => 'id',
            'snapshot_type' => array('snapshot_id', 'description_category_id', 'type_id', 'unique' => 1),
        ),
        ':options' => array('charset' => 'utf8mb4', 'collate' => 'utf8mb4_general_ci'),
    ),
    'shop_migrate_ozon_category_map' => array(
        'id' => array('int', 11, 'unsigned' => 1, 'null' => 0, 'autoincrement' => 1),
        'snapshot_id' => array('int', 11, 'unsigned' => 1, 'null' => 0),
        'description_category_id' => array('bigint', 20, 'unsigned' => 1, 'null' => 0),
        'mode' => array('varchar', 16, 'null' => 0, 'default' => 'auto'),
        'shop_category_id' => array('int', 11, 'unsigned' => 1),
        'action' => array('varchar', 16, 'null' => 0, 'default' => 'auto'),
        'created_at' => array('datetime', 'null' => 0),
        'updated_at' => array('datetime', 'null' => 0),
        ':keys' => array(
            'PRIMARY' => 'id',
            'snapshot_category' => array('snapshot_id', 'description_category_id', 'unique' => 1),
        ),
        ':options' => array('charset' => 'utf8mb4', 'collate' => 'utf8mb4_general_ci'),
    ),
    'shop_migrate_ozon_stock_map' => array(
        'id' => array('int', 11, 'unsigned' => 1, 'null' => 0, 'autoincrement' => 1),
        'snapshot_id' => array('int', 11, 'unsigned' => 1, 'null' => 0),
        'warehouse_id' => array('bigint', 20, 'unsigned' => 1, 'null' => 0),
        'mode' => array('varchar', 16, 'null' => 0, 'default' => 'auto'),
        'shop_stock_id' => array('int', 11, 'unsigned' => 1),
        'action' => array('varchar', 16, 'null' => 0, 'default' => 'auto'),
        'created_at' => array('datetime', 'null' => 0),
        'updated_at' => array('datetime', 'null' => 0),
        ':keys' => array(
            'PRIMARY' => 'id',
            'snapshot_stock' => array('snapshot_id', 'warehouse_id', 'unique' => 1),
        ),
        ':options' => array('charset' => 'utf8mb4', 'collate' => 'utf8mb4_general_ci'),
    ),
    'shop_migrate_ozon_feature_map' => array(
        'id' => array('int', 11, 'unsigned' => 1, 'null' => 0, 'autoincrement' => 1),
        'snapshot_id' => array('int', 11, 'unsigned' => 1, 'null' => 0),
        'attribute_id' => array('bigint', 20, 'unsigned' => 1, 'null' => 0),
        'mode' => array('varchar', 16, 'null' => 0, 'default' => 'auto'),
        'shop_feature_id' => array('int', 11, 'unsigned' => 1),
        'shop_feature_code' => array('varchar', 64),
        'action' => array('varchar', 16, 'null' => 0, 'default' => 'auto'),
        'created_at' => array('datetime', 'null' => 0),
        'updated_at' => array('datetime', 'null' => 0),
        ':keys' => array(
            'PRIMARY' => 'id',
            'snapshot_feature' => array('snapshot_id', 'attribute_id', 'unique' => 1),
        ),
        ':options' => array('charset' => 'utf8mb4', 'collate' => 'utf8mb4_general_ci'),
    ),
    'shop_migrate_ozon_product_map' => array(
        'id' => array('int', 11, 'unsigned' => 1, 'null' => 0, 'autoincrement' => 1),
        'offer_id' => array('varchar', 128, 'null' => 0, 'default' => ''),
        'shop_product_id' => array('int', 11, 'unsigned' => 1, 'null' => 0),
        'shop_sku_id' => array('int', 11, 'unsigned' => 1),
        'ozon_product_id' => array('bigint', 20, 'unsigned' => 1),
        'created_at' => array('datetime', 'null' => 0),
        'updated_at' => array('datetime', 'null' => 0),
        ':keys' => array(
            'PRIMARY' => 'id',
            'offer_unique' => array('offer_id', 'unique' => 1),
        ),
        ':options' => array('charset' => 'utf8mb4', 'collate' => 'utf8mb4_general_ci'),
    ),

/**
 * Wildberries snapshot, mapping, import-run and persistent link tables.
 *
 * Source names are deliberately not used as identifiers: every relation keeps
 * the corresponding WB ID so that renaming a subject or characteristic does
 * not break an existing mapping.
 */
    'shop_migrate_wb_snapshots' => array(
        'id' => array('int', 11, 'unsigned' => 1, 'null' => 0, 'autoincrement' => 1),
        'status' => array('varchar', 24, 'null' => 0, 'default' => 'building'),
        'phase' => array('varchar', 32, 'null' => 0, 'default' => 'cards'),
        'meta' => array('longtext'),
        'created_at' => array('datetime', 'null' => 0),
        'updated_at' => array('datetime', 'null' => 0),
        ':keys' => array(
            'PRIMARY' => 'id',
            'status' => 'status',
        ),
        ':options' => array('charset' => 'utf8mb4', 'collate' => 'utf8mb4_general_ci'),
    ),
    'shop_migrate_wb_parents' => array(
        'id' => array('int', 11, 'unsigned' => 1, 'null' => 0, 'autoincrement' => 1),
        'snapshot_id' => array('int', 11, 'unsigned' => 1, 'null' => 0),
        'parent_id' => array('int', 11, 'unsigned' => 1, 'null' => 0),
        'name' => array('varchar', 255, 'null' => 0, 'default' => ''),
        'is_visible' => array('tinyint', 1, 'null' => 0, 'default' => '1'),
        ':keys' => array(
            'PRIMARY' => 'id',
            'snapshot_parent' => array('snapshot_id', 'parent_id', 'unique' => 1),
        ),
        ':options' => array('charset' => 'utf8mb4', 'collate' => 'utf8mb4_general_ci'),
    ),
    'shop_migrate_wb_subjects' => array(
        'id' => array('int', 11, 'unsigned' => 1, 'null' => 0, 'autoincrement' => 1),
        'snapshot_id' => array('int', 11, 'unsigned' => 1, 'null' => 0),
        'subject_id' => array('int', 11, 'unsigned' => 1, 'null' => 0),
        'parent_id' => array('int', 11, 'unsigned' => 1, 'null' => 0),
        'name' => array('varchar', 255, 'null' => 0, 'default' => ''),
        'parent_name' => array('varchar', 255, 'null' => 0, 'default' => ''),
        'products_count' => array('int', 11, 'unsigned' => 1, 'null' => 0, 'default' => '0'),
        ':keys' => array(
            'PRIMARY' => 'id',
            'snapshot_subject' => array('snapshot_id', 'subject_id', 'unique' => 1),
            'snapshot_parent' => array('snapshot_id', 'parent_id'),
        ),
        ':options' => array('charset' => 'utf8mb4', 'collate' => 'utf8mb4_general_ci'),
    ),
    'shop_migrate_wb_cards' => array(
        'id' => array('int', 11, 'unsigned' => 1, 'null' => 0, 'autoincrement' => 1),
        'snapshot_id' => array('int', 11, 'unsigned' => 1, 'null' => 0),
        'nm_id' => array('bigint', 20, 'unsigned' => 1, 'null' => 0),
        'imt_id' => array('bigint', 20, 'unsigned' => 1, 'null' => 0, 'default' => '0'),
        'nm_uuid' => array('varchar', 64),
        'subject_id' => array('int', 11, 'unsigned' => 1, 'null' => 0),
        'parent_id' => array('int', 11, 'unsigned' => 1, 'null' => 0, 'default' => '0'),
        'vendor_code' => array('varchar', 128, 'null' => 0, 'default' => ''),
        'brand' => array('varchar', 255, 'null' => 0, 'default' => ''),
        'name' => array('varchar', 255, 'null' => 0, 'default' => ''),
        'description' => array('longtext'),
        'details' => array('longtext'),
        'wb_created_at' => array('datetime'),
        'wb_updated_at' => array('datetime'),
        'created_at' => array('datetime', 'null' => 0),
        'updated_at' => array('datetime', 'null' => 0),
        ':keys' => array(
            'PRIMARY' => 'id',
            'snapshot_nm' => array('snapshot_id', 'nm_id', 'unique' => 1),
            'snapshot_imt' => array('snapshot_id', 'imt_id', 'nm_id'),
            'snapshot_subject' => array('snapshot_id', 'subject_id'),
        ),
        ':options' => array('charset' => 'utf8mb4', 'collate' => 'utf8mb4_general_ci'),
    ),
    'shop_migrate_wb_sizes' => array(
        'id' => array('int', 11, 'unsigned' => 1, 'null' => 0, 'autoincrement' => 1),
        'snapshot_id' => array('int', 11, 'unsigned' => 1, 'null' => 0),
        'nm_id' => array('bigint', 20, 'unsigned' => 1, 'null' => 0),
        'chrt_id' => array('bigint', 20, 'unsigned' => 1, 'null' => 0),
        'tech_size' => array('varchar', 128, 'null' => 0, 'default' => ''),
        'wb_size' => array('varchar', 128, 'null' => 0, 'default' => ''),
        'barcodes' => array('text'),
        'details' => array('text'),
        ':keys' => array(
            'PRIMARY' => 'id',
            'snapshot_chrt' => array('snapshot_id', 'chrt_id', 'unique' => 1),
            'snapshot_nm' => array('snapshot_id', 'nm_id'),
        ),
        ':options' => array('charset' => 'utf8mb4', 'collate' => 'utf8mb4_general_ci'),
    ),
    'shop_migrate_wb_attributes' => array(
        'id' => array('int', 11, 'unsigned' => 1, 'null' => 0, 'autoincrement' => 1),
        'snapshot_id' => array('int', 11, 'unsigned' => 1, 'null' => 0),
        'subject_id' => array('int', 11, 'unsigned' => 1, 'null' => 0),
        'characteristic_id' => array('bigint', 20, 'unsigned' => 1, 'null' => 0),
        'name' => array('varchar', 255, 'null' => 0, 'default' => ''),
        'type' => array('varchar', 64, 'null' => 0, 'default' => ''),
        'unit' => array('varchar', 64),
        'is_required' => array('tinyint', 1, 'null' => 0, 'default' => '0'),
        'max_count' => array('int', 11, 'unsigned' => 1, 'null' => 0, 'default' => '1'),
        'meta' => array('text'),
        ':keys' => array(
            'PRIMARY' => 'id',
            'snapshot_characteristic' => array('snapshot_id', 'subject_id', 'characteristic_id', 'unique' => 1),
        ),
        ':options' => array('charset' => 'utf8mb4', 'collate' => 'utf8mb4_general_ci'),
    ),
    'shop_migrate_wb_attribute_values' => array(
        'id' => array('int', 11, 'unsigned' => 1, 'null' => 0, 'autoincrement' => 1),
        'snapshot_id' => array('int', 11, 'unsigned' => 1, 'null' => 0),
        'nm_id' => array('bigint', 20, 'unsigned' => 1, 'null' => 0),
        'subject_id' => array('int', 11, 'unsigned' => 1, 'null' => 0),
        'characteristic_id' => array('bigint', 20, 'unsigned' => 1, 'null' => 0),
        'name' => array('varchar', 255, 'null' => 0, 'default' => ''),
        'value' => array('longtext'),
        ':keys' => array(
            'PRIMARY' => 'id',
            'snapshot_value' => array('snapshot_id', 'nm_id', 'characteristic_id', 'unique' => 1),
            'snapshot_characteristic' => array('snapshot_id', 'subject_id', 'characteristic_id'),
        ),
        ':options' => array('charset' => 'utf8mb4', 'collate' => 'utf8mb4_general_ci'),
    ),
    'shop_migrate_wb_prices' => array(
        'id' => array('int', 11, 'unsigned' => 1, 'null' => 0, 'autoincrement' => 1),
        'snapshot_id' => array('int', 11, 'unsigned' => 1, 'null' => 0),
        'nm_id' => array('bigint', 20, 'unsigned' => 1, 'null' => 0),
        'chrt_id' => array('bigint', 20, 'unsigned' => 1, 'null' => 0, 'default' => '0'),
        'tech_size' => array('varchar', 128, 'null' => 0, 'default' => ''),
        'currency' => array('varchar', 8, 'null' => 0, 'default' => 'RUB'),
        'price' => array('decimal', "15,4"),
        'discounted_price' => array('decimal', "15,4"),
        'club_discounted_price' => array('decimal', "15,4"),
        'details' => array('text'),
        ':keys' => array(
            'PRIMARY' => 'id',
            'snapshot_size' => array('snapshot_id', 'nm_id', 'chrt_id', 'tech_size', 'unique' => 1),
            'snapshot_chrt' => array('snapshot_id', 'chrt_id'),
        ),
        ':options' => array('charset' => 'utf8mb4', 'collate' => 'utf8mb4_general_ci'),
    ),
    'shop_migrate_wb_warehouses' => array(
        'id' => array('int', 11, 'unsigned' => 1, 'null' => 0, 'autoincrement' => 1),
        'snapshot_id' => array('int', 11, 'unsigned' => 1, 'null' => 0),
        'warehouse_key' => array('varchar', 80, 'null' => 0),
        'source' => array('varchar', 16, 'null' => 0, 'default' => 'seller'),
        'warehouse_id' => array('bigint', 20, 'unsigned' => 1, 'null' => 0),
        'name' => array('varchar', 255, 'null' => 0, 'default' => ''),
        'details' => array('text'),
        ':keys' => array(
            'PRIMARY' => 'id',
            'snapshot_warehouse' => array('snapshot_id', 'warehouse_key', 'unique' => 1),
        ),
        ':options' => array('charset' => 'utf8mb4', 'collate' => 'utf8mb4_general_ci'),
    ),
    'shop_migrate_wb_stocks' => array(
        'id' => array('int', 11, 'unsigned' => 1, 'null' => 0, 'autoincrement' => 1),
        'snapshot_id' => array('int', 11, 'unsigned' => 1, 'null' => 0),
        'warehouse_key' => array('varchar', 80, 'null' => 0),
        'nm_id' => array('bigint', 20, 'unsigned' => 1, 'null' => 0, 'default' => '0'),
        'chrt_id' => array('bigint', 20, 'unsigned' => 1, 'null' => 0),
        'quantity' => array('decimal', "15,3", 'null' => 0, 'default' => '0.000'),
        'in_way_to_client' => array('decimal', "15,3", 'null' => 0, 'default' => '0.000'),
        'in_way_from_client' => array('decimal', "15,3", 'null' => 0, 'default' => '0.000'),
        'details' => array('text'),
        ':keys' => array(
            'PRIMARY' => 'id',
            'snapshot_stock' => array('snapshot_id', 'warehouse_key', 'chrt_id', 'unique' => 1),
            'snapshot_chrt' => array('snapshot_id', 'chrt_id'),
        ),
        ':options' => array('charset' => 'utf8mb4', 'collate' => 'utf8mb4_general_ci'),
    ),
    'shop_migrate_wb_type_map' => array(
        'id' => array('int', 11, 'unsigned' => 1, 'null' => 0, 'autoincrement' => 1),
        'snapshot_id' => array('int', 11, 'unsigned' => 1, 'null' => 0),
        'parent_id' => array('int', 11, 'unsigned' => 1, 'null' => 0),
        'subject_id' => array('int', 11, 'unsigned' => 1, 'null' => 0),
        'mode' => array('varchar', 16, 'null' => 0, 'default' => 'auto'),
        'action' => array('varchar', 16, 'null' => 0, 'default' => 'auto'),
        'shop_type_id' => array('int', 11, 'unsigned' => 1),
        'shop_type_name' => array('varchar', 255),
        'created_at' => array('datetime', 'null' => 0),
        'updated_at' => array('datetime', 'null' => 0),
        ':keys' => array(
            'PRIMARY' => 'id',
            'snapshot_subject' => array('snapshot_id', 'subject_id', 'unique' => 1),
        ),
        ':options' => array('charset' => 'utf8mb4', 'collate' => 'utf8mb4_general_ci'),
    ),
    'shop_migrate_wb_category_map' => array(
        'id' => array('int', 11, 'unsigned' => 1, 'null' => 0, 'autoincrement' => 1),
        'snapshot_id' => array('int', 11, 'unsigned' => 1, 'null' => 0),
        'entity_type' => array('varchar', 16, 'null' => 0, 'default' => 'subject'),
        'wb_id' => array('int', 11, 'unsigned' => 1, 'null' => 0),
        'parent_id' => array('int', 11, 'unsigned' => 1, 'null' => 0, 'default' => '0'),
        'mode' => array('varchar', 16, 'null' => 0, 'default' => 'auto'),
        'action' => array('varchar', 16, 'null' => 0, 'default' => 'auto'),
        'shop_category_id' => array('int', 11, 'unsigned' => 1),
        'created_at' => array('datetime', 'null' => 0),
        'updated_at' => array('datetime', 'null' => 0),
        ':keys' => array(
            'PRIMARY' => 'id',
            'snapshot_entity' => array('snapshot_id', 'entity_type', 'wb_id', 'unique' => 1),
        ),
        ':options' => array('charset' => 'utf8mb4', 'collate' => 'utf8mb4_general_ci'),
    ),
    'shop_migrate_wb_feature_map' => array(
        'id' => array('int', 11, 'unsigned' => 1, 'null' => 0, 'autoincrement' => 1),
        'snapshot_id' => array('int', 11, 'unsigned' => 1, 'null' => 0),
        'subject_id' => array('int', 11, 'unsigned' => 1, 'null' => 0),
        'characteristic_id' => array('bigint', 20, 'unsigned' => 1, 'null' => 0),
        'mode' => array('varchar', 16, 'null' => 0, 'default' => 'auto'),
        'action' => array('varchar', 16, 'null' => 0, 'default' => 'auto'),
        'shop_feature_id' => array('int', 11, 'unsigned' => 1),
        'shop_feature_code' => array('varchar', 64),
        'created_at' => array('datetime', 'null' => 0),
        'updated_at' => array('datetime', 'null' => 0),
        ':keys' => array(
            'PRIMARY' => 'id',
            'snapshot_characteristic' => array('snapshot_id', 'subject_id', 'characteristic_id', 'unique' => 1),
        ),
        ':options' => array('charset' => 'utf8mb4', 'collate' => 'utf8mb4_general_ci'),
    ),
    'shop_migrate_wb_stock_map' => array(
        'id' => array('int', 11, 'unsigned' => 1, 'null' => 0, 'autoincrement' => 1),
        'snapshot_id' => array('int', 11, 'unsigned' => 1, 'null' => 0),
        'warehouse_key' => array('varchar', 80, 'null' => 0),
        'mode' => array('varchar', 16, 'null' => 0, 'default' => 'auto'),
        'action' => array('varchar', 16, 'null' => 0, 'default' => 'auto'),
        'shop_stock_id' => array('int', 11, 'unsigned' => 1),
        'created_at' => array('datetime', 'null' => 0),
        'updated_at' => array('datetime', 'null' => 0),
        ':keys' => array(
            'PRIMARY' => 'id',
            'snapshot_warehouse' => array('snapshot_id', 'warehouse_key', 'unique' => 1),
        ),
        ':options' => array('charset' => 'utf8mb4', 'collate' => 'utf8mb4_general_ci'),
    ),
    'shop_migrate_wb_product_map' => array(
        'id' => array('int', 11, 'unsigned' => 1, 'null' => 0, 'autoincrement' => 1),
        // Collision-free importer group: imtID * 2, or nmID * 2 + 1
        // when WB did not provide an imtID. Raw WB IDs stay in separate fields.
        'group_id' => array('bigint', 20, 'unsigned' => 1, 'null' => 0),
        'imt_id' => array('bigint', 20, 'unsigned' => 1, 'null' => 0, 'default' => '0'),
        'nm_id' => array('bigint', 20, 'unsigned' => 1, 'null' => 0, 'default' => '0'),
        'shop_product_id' => array('int', 11, 'unsigned' => 1, 'null' => 0),
        // NULL means that the first import has not reached product finalize.
        'completed_at' => array('datetime'),
        'created_at' => array('datetime', 'null' => 0),
        'updated_at' => array('datetime', 'null' => 0),
        ':keys' => array(
            'PRIMARY' => 'id',
            'group_unique' => array('group_id', 'unique' => 1),
            'imt_id' => 'imt_id',
            'nm_id' => 'nm_id',
            'shop_product' => 'shop_product_id',
        ),
        ':options' => array('charset' => 'utf8mb4', 'collate' => 'utf8mb4_general_ci'),
    ),
    'shop_migrate_wb_sku_map' => array(
        'id' => array('int', 11, 'unsigned' => 1, 'null' => 0, 'autoincrement' => 1),
        'nm_id' => array('bigint', 20, 'unsigned' => 1, 'null' => 0),
        'chrt_id' => array('bigint', 20, 'unsigned' => 1, 'null' => 0),
        'shop_product_id' => array('int', 11, 'unsigned' => 1, 'null' => 0),
        'shop_sku_id' => array('int', 11, 'unsigned' => 1, 'null' => 0),
        'created_at' => array('datetime', 'null' => 0),
        'updated_at' => array('datetime', 'null' => 0),
        ':keys' => array(
            'PRIMARY' => 'id',
            'chrt_unique' => array('chrt_id', 'unique' => 1),
            'nm_chrt' => array('nm_id', 'chrt_id'),
            'shop_product' => 'shop_product_id',
        ),
        ':options' => array('charset' => 'utf8mb4', 'collate' => 'utf8mb4_general_ci'),
    ),
    'shop_migrate_wb_image_map' => array(
        'id' => array('int', 11, 'unsigned' => 1, 'null' => 0, 'autoincrement' => 1),
        'nm_id' => array('bigint', 20, 'unsigned' => 1, 'null' => 0),
        'source_key' => array('char', 40, 'null' => 0),
        'shop_product_id' => array('int', 11, 'unsigned' => 1, 'null' => 0),
        'shop_image_id' => array('int', 11, 'unsigned' => 1, 'null' => 0),
        'max_dimension' => array('smallint', 5, 'unsigned' => 1, 'null' => 0, 'default' => '0'),
        'created_at' => array('datetime', 'null' => 0),
        ':keys' => array(
            'PRIMARY' => 'id',
            'source_unique' => array('shop_product_id', 'source_key', 'unique' => 1),
            'shop_product' => 'shop_product_id',
        ),
        ':options' => array('charset' => 'utf8mb4', 'collate' => 'utf8mb4_general_ci'),
    ),
    'shop_migrate_wb_unpriced_products' => array(
        'run_id' => array('int', 11, 'unsigned' => 1, 'null' => 0),
        'shop_product_id' => array('int', 11, 'unsigned' => 1, 'null' => 0),
        'snapshot_id' => array('int', 11, 'unsigned' => 1, 'null' => 0),
        ':keys' => array(
            'PRIMARY' => array('run_id', 'shop_product_id'),
            'snapshot_id' => 'snapshot_id',
        ),
        ':options' => array('charset' => 'utf8mb4', 'collate' => 'utf8mb4_general_ci'),
    ),
    'shop_migrate_wb_runs' => array(
        'id' => array('int', 11, 'unsigned' => 1, 'null' => 0, 'autoincrement' => 1),
        'snapshot_id' => array('int', 11, 'unsigned' => 1, 'null' => 0),
        'kind' => array('varchar', 16, 'null' => 0, 'default' => 'products'),
        'status' => array('varchar', 24, 'null' => 0, 'default' => 'running'),
        'cursor' => array('int', 11, 'unsigned' => 1, 'null' => 0, 'default' => '0'),
        'current_group_id' => array('bigint', 20, 'unsigned' => 1, 'null' => 0, 'default' => '0'),
        'image_offset' => array('int', 11, 'unsigned' => 1, 'null' => 0, 'default' => '0'),
        'cancel_requested' => array('tinyint', 1, 'null' => 0, 'default' => '0'),
        'options' => array('longtext'),
        'counters' => array('longtext'),
        'error' => array('text'),
        'created_at' => array('datetime', 'null' => 0),
        'updated_at' => array('datetime', 'null' => 0),
        'finished_at' => array('datetime'),
        ':keys' => array(
            'PRIMARY' => 'id',
            'snapshot_status' => array('snapshot_id', 'status'),
        ),
        ':options' => array('charset' => 'utf8mb4', 'collate' => 'utf8mb4_general_ci'),
    ),
);
